services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  app:
    # build: .
    image: supakornsupakorn/schoolmange
    container_name: nextjs_app
    ports:
      - "3000" # ไม่ต้องใส่ port หรือ host ให้เพราะเราจะใช้ Nginx ในการ reverse proxy
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydb # Change localhost to postgres
    depends_on:
      - postgres
    networks:
      - db_network
      - web_network

  pgadmin-school:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-school
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
